---

- name: Adding latest stable nginx repository
  apt_repository: repo='ppa:nginx/stable'

- name: Ensure nginx installed
  apt: update_cache=yes name=nginx state=present

- name: Copy nginx config with logging capabilities to graylog server
  template: src=templates/nginx.j2 dest=/etc/nginx/nginx.conf

- name: Ensure nginx service running
  service: name=nginx state=restarted
